[tool.poetry]
name = "gz-ocean-momentum"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "gz_ocean_momentum"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
xarray = {extras = ["io"], version = "^2023.2.0"}
mlflow-skinny = "^2.1.1"
dask = "^2023.1.1"
intake = "^0.6.6"
requests = "^2.28.2"
aiohttp = "^3.8.3"
intake-xarray = "^0.6.1"
gcsfs = "^2023.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
