- lat-min: 35
  lat-max: 50
  long-min: -50
  long-max: -20
- lat-min: -40
  lat-max: -25
  long-min: -180
  long-max: -162
- lat-min: -20
  lat-max: -5
  long-min: -110
  long-max: -92
- lat-min: -0
  lat-max: 15
  long-min: -48
  long-max: -30
