in-train-data-dir: /home/raehik/sh/gz21/gz21/tmp/generated/forcings/paper-n100
subdomains-file: /home/raehik/sh/gz21/gz21/examples/cli-configs/training-subdomains-paper.yaml

batch-size: 4

epochs: 20
initial-learning-rate: 5.0e-4
decay-factor: 0.0
decay-at-epoch-milestones: [15, 30] # TODO is 0 implicit? I forget

train-split: 0.8
test-split:  0.85
