name: CI

on:
  # run on every push to main
  push:
    branches:
    - main
  # run on every push (not commit) to a PR, plus open/reopen
  pull_request:
    types:
    - synchronize
    - opened
    - reopened

jobs:
  linux-build:
    name: Build & test (${{ matrix.python-version }} | ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      # continue testing other configurations even if a matrix job fails
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10", "3.9", "3.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: sudo apt install libgeos-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy>=1.0 pytest
        python -m pip install .

    - name: mypy
      if: always()
      run: mypy --strict .

    - name: Run tests
      if: always()
      run: pytest .

  mac-build:
    name: Build & test (${{ matrix.python-version }} | ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      # continue testing other configurations even if a matrix job fails
      fail-fast: false
      matrix:
        os: ["macos-latest"]
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: brew install geos

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy>=1.0 pytest
        python -m pip install .

    - name: Run tests
      if: always()
      run: pytest .
