name: Checks
on:
  push:
    branches:
      - "master"
      - "cleanup_jwa"
  pull_request:
    branches:
      - "*"

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install black>=23 pylint>=2.16 mypy>=1.0 pydocstyle>=6.3
    - run: pylint --disable=all --enable=unused-import .
    - run: mypy --strict .
    - run: pydocstyle --convention=numpy .
